name: Deploy to DockerHub
on:
  workflow_dispatch:
    inputs:
      tag:
        description: docker tag
        required: false
env:
  DOCKER_IMAGE_NAME: parseltongist/bank_app
  DOCKERFILE_DIRECTORY: ./
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_NAME:${{ inputs.tag }} .
        working-directory: ${{ env.DOCKERFILE_DIRECTORY }}
      - name: Install Docker Credential Helper
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-credential-helpers
      - name: Configure Docker to user credentials helper
        run: |
          echo '{ "credsStore": "secretservice" }' > ~/.docker/config.json
      - name: Log in to Docker Hub
        if: success()
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} |
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Push Docker image to the Docker Hub
        if: success()
        run: docker push $DOCKER_IMAGE_NAME:${{ inputs.tag }}
        working-directory: ${{ env.DOCKERFILE_DIRECTORY }}
