---
name: Deploy to DockerHub
on:
  workflow_dispatch:
    inputs:
      tag:
        description: docker tag
        required: true
        default: "latest"
env:
  DOCKER_IMAGE_NAME: parseltongist/bank_app
  DOCKERFILE_DIRECTORY: ./
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        if: success()
        run: |
          docker build -t $DOCKER_IMAGE_NAME:${{ inputs.tag }} .
        working-directory: ${{ env.DOCKERFILE_DIRECTORY }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to the Docker Hub
        if: success()
        run: docker push $DOCKER_IMAGE_NAME:${{ inputs.tag }}
        working-directory: ${{ env.DOCKERFILE_DIRECTORY }}
