---
name: Docker build and tests
on:
  pull_request:
env:
  DOCKER_IMAGE_NAME: parseltongist/bank_app
  DOCKERFILE_DIRECTORY: ./
jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        # $GITHUB_HEAD_REF works only with pull_request trigger
        run: |
          docker build -t test-tag --build-arg="branch=$GITHUB_HEAD_REF" .
        working-directory: ${{ env.DOCKERFILE_DIRECTORY }}
      - name: Run tests via Docker
        run: |
          docker run test-tag -c "
            /app/venv/bin/python -m unittest discover bank_app
          "
